/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DocumentoDAO;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Documento;
import modelo.PalavraChave;
import modelo.Usuario;


public class CadastrarDocumento extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDocumento1
     */
    public CadastrarDocumento(Usuario usuario) {
        initComponents();
        setExtendedState(CadastrarDocumento.MAXIMIZED_BOTH);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/InterfaceGUI/imagens/logo-ufal.jpg")));
        this.setTitle("Alagoas Histórica Digital");
        this.usuario = usuario;
        txtResponsavel.setText(this.usuario.getLogin());
    }

    public CadastrarDocumento() {
        initComponents();
        setExtendedState(CadastrarDocumento.MAXIMIZED_BOTH);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/InterfaceGUI/imagens/logo-ufal.jpg")));
        this.setTitle("Alagoas Histórica Digital");
    }

    public CadastrarDocumento(Usuario usuario, Documento doc, List<PalavraChave> palavrasChave) {
        initComponents();
        setExtendedState(CadastrarDocumento.MAXIMIZED_BOTH);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/InterfaceGUI/imagens/logo-ufal.jpg")));
        this.setTitle("Alagoas Histórica Digital");
        this.usuario = usuario;
        txtResponsavel.setText(this.usuario.getLogin());
        this.palavrasSelecionadas = palavrasChave;

        txtImagem.setText(doc.getImagem());
        txtOrganizacao.setText(doc.getOrganizacao());
        txtPreenchimento.setText(doc.getPreenchimento());
        txtRevisao.setText(doc.getRevisao());
        txtEspecie.setText(doc.getEspecie());
        txtDataInicial.setText(doc.getDataInicial());
        txtDataFinal.setText(doc.getDataFinal());
        txtQuantidade.setText(doc.getQuantidade());
        txtConservacao.setText(doc.getConservacao());
        txtDescricao.setText(doc.getDescricao());
        txtObservacao.setText(doc.getObservacao());
        txtIdentificacaoDocumento.setText(doc.getIdentificacaoDocumento());
        txtProveniencia.setText(doc.getProveniencia());
        txtLocalizacao.setText(doc.getLocalizacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        labelAtualizacaodedadosdodocumento = new javax.swing.JLabel();
        labelnumerododocumento = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labelUnidadedearmazenamento = new javax.swing.JLabel();
        Organização = new javax.swing.JLabel();
        txtOrganizacao = new javax.swing.JTextField();
        labelProveniencia = new javax.swing.JLabel();
        txtProveniencia = new javax.swing.JTextField();
        labelMudarnumerododocumento = new javax.swing.JLabel();
        txtIdentificacaoDocumento = new javax.swing.JTextField();
        labelPreenchimento = new javax.swing.JLabel();
        txtPreenchimento = new javax.swing.JTextField();
        labelResponsabilidade = new javax.swing.JLabel();
        labelRevisao = new javax.swing.JLabel();
        txtRevisao = new javax.swing.JTextField();
        labelResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        labelDescricaodoconjuntodocumental = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        labelEspecie = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        labelDatainicial = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        labelDatafinal = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        labelConservacao = new javax.swing.JLabel();
        txtConservacao = new javax.swing.JTextField();
        labelDescricoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        labelObservacoes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnCadastrarPalavraChave = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtImagem = new javax.swing.JTextArea();
        LabelLocalizacao = new javax.swing.JLabel();
        txtLocalizacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAtualizacaodedadosdodocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAtualizacaodedadosdodocumento.setText("Cadastrar documento");

        labelnumerododocumento.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelnumerododocumento.setText("Imagem");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/diretorio.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelUnidadedearmazenamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelUnidadedearmazenamento.setText("Unidade de armazenamento:");

        Organização.setText("Organização:");

        labelProveniencia.setText("Proveniência:");

        labelMudarnumerododocumento.setText("Nº do documento:");

        labelPreenchimento.setText("Preenchimento:");

        labelResponsabilidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelResponsabilidade.setText("Responsabilidade:");

        labelRevisao.setText("Revisão:");

        labelResponsavel.setText("Responsável:");

        txtResponsavel.setEditable(false);

        labelDescricaodoconjuntodocumental.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDescricaodoconjuntodocumental.setText("Descrição do conjunto documental:");

        labelQuantidade.setText("Quantidade:");

        labelEspecie.setText("Espécie:");

        labelDatainicial.setText("Data inicial:");

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####    ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelDatafinal.setText("Data final:");

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelConservacao.setText("Conservação:");

        labelDescricoes.setText("Descrições:");

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        labelObservacoes.setText("Observações:");

        txtObservacao.setColumns(20);
        txtObservacao.setLineWrap(true);
        txtObservacao.setRows(5);
        jScrollPane2.setViewportView(txtObservacao);

        btnCadastrarPalavraChave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/addChave.png"))); // NOI18N
        btnCadastrarPalavraChave.setText("Cadastrar palavras chaves do documento");
        btnCadastrarPalavraChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPalavraChaveActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/voltar.png"))); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtImagem.setColumns(20);
        txtImagem.setLineWrap(true);
        txtImagem.setRows(5);
        jScrollPane3.setViewportView(txtImagem);

        LabelLocalizacao.setText("Localização:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUnidadedearmazenamento)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProveniencia)
                                    .addComponent(Organização)
                                    .addComponent(LabelLocalizacao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrganizacao)
                                    .addComponent(txtProveniencia)
                                    .addComponent(txtLocalizacao))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPreenchimento)
                                            .addComponent(labelRevisao)
                                            .addComponent(labelResponsavel))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelMudarnumerododocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtResponsavel)
                                    .addComponent(txtRevisao)
                                    .addComponent(txtPreenchimento)
                                    .addComponent(txtIdentificacaoDocumento))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(labelResponsabilidade)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelQuantidade))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelEspecie)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtEspecie))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDatainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDatafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelConservacao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE))
                                            .addComponent(txtConservacao)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDescricoes)
                                            .addComponent(btnCadastrarPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelObservacoes)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnCancelar)
                                                    .addGap(68, 68, 68)
                                                    .addComponent(btnLimpar)
                                                    .addGap(68, 68, 68)
                                                    .addComponent(btnSalvar))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(labelDescricaodoconjuntodocumental))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnumerododocumento)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(719, 719, 719)
                                .addComponent(labelAtualizacaodedadosdodocumento)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addGap(20, 20, 20))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAtualizacaodedadosdodocumento)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelnumerododocumento)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUnidadedearmazenamento)
                            .addComponent(labelResponsabilidade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Organização)
                            .addComponent(txtOrganizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProveniencia)
                            .addComponent(txtProveniencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLocalizacao)
                            .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelMudarnumerododocumento)
                                    .addComponent(txtIdentificacaoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPreenchimento)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRevisao)
                            .addComponent(txtRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelResponsavel)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescricaodoconjuntodocumental)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(labelEspecie)
                    .addComponent(labelDatainicial)
                    .addComponent(labelDatafinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelConservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObservacoes)
                    .addComponent(labelDescricoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrarPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            Diretorio d = new Diretorio();
            d.visible();
            diretorios = d.pegarDiretorio();

            if(diretorios != null){
                for (int i = 0; i < diretorios.length; i++) {
                    txtImagem.setText(txtImagem.getText().concat(diretorios[i].toString()).concat(";"));
                }
            }
            else{
                txtImagem.setText("");
            }

        } catch (Exception ex) {
            Logger.getLogger(CadastrarDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCadastrarPalavraChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPalavraChaveActionPerformed


        Documento doc = new Documento(txtImagem.getText(), txtProveniencia.getText(), txtOrganizacao.getText(),
                txtEspecie.getText(), txtQuantidade.getText(), txtConservacao.getText(), txtDescricao.getText(),
                txtObservacao.getText(), txtPreenchimento.getText(), txtRevisao.getText(),
                usuario.getLogin(), txtDataFinal.getText(), txtDataInicial.getText(),
                usuario, txtIdentificacaoDocumento.getText(), txtLocalizacao.getText());

        new PalavrasChaveDocumento(usuario, doc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarPalavraChaveActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new Principal(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparTela();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!txtOrganizacao.getText().equals("") && !txtProveniencia.getText().equals("")
                && !txtEspecie.getText().equals("") && !txtDataInicial.getText().equals("")
                && !txtQuantidade.getText().equals("") && !txtConservacao.getText().equals("")
                && !txtDescricao.getText().equals("") && !txtObservacao.getText().equals("")
                && !txtDataFinal.getText().equals("") && !txtPreenchimento.getText().equals("")
                && !txtRevisao.getText().equals("") && !txtResponsavel.getText().equals("")
                && !txtImagem.getText().equals("") && !palavrasSelecionadas.isEmpty()
                && !txtIdentificacaoDocumento.getText().equals("") && !txtLocalizacao.getText().equals("")) {

            try {

                Documento doc = new Documento(txtImagem.getText(), txtProveniencia.getText(), txtOrganizacao.getText(),
                        txtEspecie.getText(), txtQuantidade.getText(), txtConservacao.getText(), txtDescricao.getText(),
                        txtObservacao.getText(), txtPreenchimento.getText(), txtRevisao.getText(),
                        usuario.getLogin(), txtDataFinal.getText(), txtDataInicial.getText(),
                        usuario, txtIdentificacaoDocumento.getText(), txtLocalizacao.getText());

                doc.setPalavras(palavrasSelecionadas);

                DocumentoDAO dDAO = new DocumentoDAO();
                dDAO.salvar(doc);

                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");                


            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao conectar com o banco");

            }


        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos e as palavras chaves do documento");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void LimparTela() {
        txtImagem.setText("");
        txtOrganizacao.setText("");
        txtPreenchimento.setText("");
        txtRevisao.setText("");
        txtEspecie.setText("");
        txtDataInicial.setText("");
        txtDataFinal.setText("");
        txtQuantidade.setText("");
        txtConservacao.setText("");
        txtDescricao.setText("");
        txtObservacao.setText("");
        txtProveniencia.setText("");
        txtIdentificacaoDocumento.setText("");
        txtLocalizacao.setText("");
        palavrasSelecionadas.clear();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLocalizacao;
    private javax.swing.JLabel Organização;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarPalavraChave;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelAtualizacaodedadosdodocumento;
    private javax.swing.JLabel labelConservacao;
    private javax.swing.JLabel labelDatafinal;
    private javax.swing.JLabel labelDatainicial;
    private javax.swing.JLabel labelDescricaodoconjuntodocumental;
    private javax.swing.JLabel labelDescricoes;
    private javax.swing.JLabel labelEspecie;
    private javax.swing.JLabel labelMudarnumerododocumento;
    private javax.swing.JLabel labelObservacoes;
    private javax.swing.JLabel labelPreenchimento;
    private javax.swing.JLabel labelProveniencia;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelResponsabilidade;
    private javax.swing.JLabel labelResponsavel;
    private javax.swing.JLabel labelRevisao;
    private javax.swing.JLabel labelUnidadedearmazenamento;
    private javax.swing.JLabel labelnumerododocumento;
    private javax.swing.JTextField txtConservacao;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtIdentificacaoDocumento;
    private javax.swing.JTextArea txtImagem;
    private javax.swing.JTextField txtLocalizacao;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtOrganizacao;
    private javax.swing.JTextField txtPreenchimento;
    private javax.swing.JTextField txtProveniencia;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtRevisao;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario;
    File[] diretorios;
    List<PalavraChave> palavrasSelecionadas = new ArrayList<>();
}
