/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.PalavraChaveDAO;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import modelo.Documento;
import modelo.Usuario;


public class PalavrasChaveDocumento extends javax.swing.JFrame {

    /**
     * Creates new form PalavrasChaveDocumento1
     */
    public PalavrasChaveDocumento(Usuario usuario, Documento doc) {
        this.doc = doc;
        this.usuario = usuario;
        initComponents();
        gerarListaPalavrasChave();
        setExtendedState(PalavrasChaveDocumento.MAXIMIZED_BOTH);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/InterfaceGUI/imagens/logo-ufal.jpg")));
        this.setTitle("Alagoas Histórica Digital");
    }

    public PalavrasChaveDocumento() {
        initComponents();
        gerarListaPalavrasChave();
        setExtendedState(PalavrasChaveDocumento.MAXIMIZED_BOTH);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/InterfaceGUI/imagens/logo-ufal.jpg")));
        this.setTitle("Alagoas Histórica Digital");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListPalavras = new javax.swing.JList();
        btnConcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Cadastrar Plavras Chaves do Documento");

        jListPalavras.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Palavra-Chave:"));
        jListPalavras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListPalavras.setVisibleRowCount(10);
        jScrollPane4.setViewportView(jListPalavras);

        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfaceGUI/imagens/voltar.png"))); // NOI18N
        btnConcluir.setText("Concluir Seleção");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConcluir)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConcluir)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        int[] palavrasSelecionadas = jListPalavras.getSelectedIndices();
        List<modelo.PalavraChave> palavrasSelec = new ArrayList<>();

        for (int i = 0; i < palavrasSelecionadas.length; i++) {
            palavrasSelec.add(palavras.get(palavrasSelecionadas[i]));
        }

        this.dispose();
        new CadastrarDocumento(usuario, doc, palavrasSelec).setVisible(true);
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void gerarListaPalavrasChave() {
        PalavraChaveDAO pDAO = new PalavraChaveDAO();
        palavras = pDAO.recuperarTodas();
        
        if (palavras != null) {
            modelo.PalavraChave[] listPalavras = new modelo.PalavraChave[palavras.size()];
            
            for (int i = 0; i < palavras.size(); i++) {
                listPalavras[i] = palavras.get(i);
            }
            
            jListPalavras.setListData(listPalavras);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListPalavras;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
    ArrayList<modelo.PalavraChave> palavras;
    Documento doc;
    Usuario usuario;
}
